In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
df = pd.read_csv('magic04.data', header=None)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19020 entries, 0 to 19019
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       19020 non-null  float64
 1   1       19020 non-null  float64
 2   2       19020 non-null  float64
 3   3       19020 non-null  float64
 4   4       19020 non-null  float64
 5   5       19020 non-null  float64
 6   6       19020 non-null  float64
 7   7       19020 non-null  float64
 8   8       19020 non-null  float64
 9   9       19020 non-null  float64
 10  10      19020 non-null  str
dtypes: float64(10), str(1)
memory usage: 1.6 MB

In [13]:
cols = ['fLength', 'fWidth', 'fSize', 'fConc', 'fConc1', 'fAsym', 'fM3Long', 'fM3Trans', 'fAlpha', 'fDist', 'class']
df = pd.read_csv('magic04.data', names=cols)
df.sample(16)

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
2290,29.5490,14.1175,2.3692,0.3590,0.1902,37.1775,19.8095,-8.8034,0.9098,145.2470,g
15003,111.3448,22.4878,2.9761,0.3863,0.2071,-109.1883,-81.0276,7.2081,18.4264,290.5854,h
5299,25.8809,14.3440,2.6330,0.4400,0.2643,-16.7370,-9.3896,9.7724,12.0537,207.2180,g
13589,13.1446,10.0064,2.3901,0.8065,0.5275,12.2071,7.8856,10.3149,7.9436,143.1090,h
12604,96.8986,25.3328,3.4313,0.1566,0.1126,-49.1577,-82.7423,-20.1229,28.1173,168.5184,h
11707,16.4733,11.3066,2.3502,0.6205,0.3549,-3.5313,7.2908,7.0545,67.3760,65.9992,g
3206,24.5360,10.2893,2.4541,0.4569,0.2302,-19.2405,18.7479,-5.4650,21.5920,139.0760,g
17309,15.5026,11.6269,2.6977,0.5482,0.2962,-4.6309,3.5972,-8.5648,32.3187,214.6567,h
5167,47.4777,18.7244,3.1276,0.2557,0.1338,33.2860,35.3095,9.0855,13.1610,162.9810,g
4029,13.0246,10.9754,2.1508,0.7562,0.4488,-14.1507,5.8998,10.2185,81.1239,179.6180,g
17353,19.7064,16.3057,2.5353,0.5673,0.4009,-5.8563,-8.7164,8.7247,68.8497,58.3880,h
11058,87.9035,25.3183,3.0752,0.2918,0.1720,-28.0846,38.0092,20.0531,3.7892,312.4460,g
1168,50.8322,24.6663,2.8707,0.2397,0.1286,-18.4173,-35.6601,-9.6560,0.8170,226.6440,g
10992,31.8437,21.3649,2.5302,0.3156,0.1578,27.0289,-14.5664,-19.8732,5.4750,106.4230,g
3840,20.3817,8.9355,2.3324,0.6419,0.4023,21.7592,13.5364,-2.8666,25.8139,138.9040,g
233,70.4570,22.9878,3.0195,0.2562,0.1496,43.5397,68.1553,-10.9792,34.2372,216.9570,g

In [40]:
df['class'] = (df['class'] == 'g').astype(int)

In [ ]:
df.sample(60)

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
10501,23.5014,18.6909,2.6972,0.3916,0.2259,-10.1244,-12.8496,-15.4183,17.8557,159.7730,0
4257,76.2697,27.5969,3.7549,0.1535,0.0891,47.7080,65.1852,-18.3947,4.0540,215.1090,0
16262,254.6375,116.4147,3.6089,0.1929,0.0856,400.2840,-224.4015,91.0362,57.8297,186.4461,0
775,63.9201,26.6873,3.7525,0.1908,0.1097,-66.1234,39.0716,13.4314,0.0350,263.5900,0
14453,113.2104,28.0599,2.8556,0.1924,0.1143,-73.6959,-100.6832,-30.3239,9.8037,259.0725,0
11570,92.7690,36.7959,4.0940,0.1000,0.0505,17.6552,82.5596,-32.9371,5.8385,227.0800,0
2117,45.5945,21.2593,3.0538,0.2102,0.1144,-19.4628,-32.9385,6.9607,9.0222,216.7460,0
10803,28.2831,19.2789,2.5502,0.5408,0.2972,28.8722,21.3541,-15.6616,45.8856,160.5030,0
2923,19.6069,9.6188,2.2577,0.5912,0.3564,-22.6862,-11.7106,-3.7514,34.1365,130.3780,0
4793,27.4601,7.0214,2.1673,0.5714,0.2891,12.6378,-5.8615,2.2142,25.7520,152.5960,0
6225,32.5109,17.1115,2.6289,0.3173,0.1704,44.7869,23.1687,-15.2572,18.1420,177.2490,0
6355,22.1635,15.3738,2.5514,0.4382,0.2261,29.7541,-9.5821,-4.5724,26.5822,110.6070,0
11562,98.5903,23.9551,3.0894,0.1669,0.0916,92.2141,98.9695,15.6326,0.1561,250.6840,0
5242,90.9536,23.7516,3.4208,0.1655,0.0837,32.9665,77.8088,-16.6045,5.7787,278.8660,0
2818,20.3260,7.2678,2.1287,0.7286,0.3829,2.2156,-9.5734,5.6060,16.5060,220.9150,0
1192,37.4704,10.7012,2.4829,0.4178,0.2220,52.0538,-10.5699,6.9543,1.9409,160.2220,0
119,13.1994,10.8032,2.2240,0.7761,0.4209,-14.5262,1.8356,-11.7029,54.0277,181.8170,0
16068,135.9170,110.8600,3.2840,0.1238,0.0632,-117.0320,100.5000,-91.7792,61.4850,202.2020,0
5899,28.5834,17.8928,2.6075,0.3852,0.1938,-31.8852,20.8792,12.0862,5.0486,71.4573,0
11165,25.4837,16.0308,2.6165,0.4111,0.2430,-9.4206,-5.4920,-9.5995,25.7230,229.1440,0
5258,64.8397,17.9677,2.9899,0.2641,0.1448,77.0910,63.8889,5.0103,3.3320,256.6860,0
18753,140.4164,39.9692,3.4607,0.1482,0.0909,-154.5634,62.0818,31.1722,42.7430,182.9054,0
1821,18.1938,12.0311,2.4257,0.5741,0.3884,2.9874,-9.6578,11.2342,7.6823,63.5566,0
18883,33.4636,26.9276,2.5392,0.3652,0.1667,-29.6361,-28.6916,-20.0277,42.9562,111.2288,0
18630,54.9452,11.3293,2.8854,0.3190,0.2012,-14.0427,-29.1187,8.0343,10.1230,65.0085,0
14266,71.3527,17.8546,3.0853,0.1749,0.0932,142.7684,-20.1101,-3.5355,16.6362,155.5068,0
2075,25.8925,15.6120,2.5179,0.3672,0.1836,27.8147,18.0106,10.1931,17.3140,134.6800,0
5020,46.8081,15.2763,2.5521,0.4404,0.2482,49.1972,-21.9238,-9.4602,1.4454,156.3830,0
5947,20.8308,12.4463,2.4338,0.4899,0.2597,-16.0768,-13.6604,8.7292,86.2162,149.0120,0
14502,87.8645,78.8819,3.2313,0.3137,0.1979,-9.2132,-114.6773,42.3665,47.6948,365.8636,0
18735,23.8869,18.7115,2.6841,0.4138,0.1923,-13.7371,18.9082,-8.1440,35.4637,58.4591,0
12250,20.6035,10.4368,2.2380,0.5896,0.3324,6.6446,-17.2788,10.1291,6.7081,95.8627,0
15227,44.0446,16.1461,2.8436,0.3066,0.1665,-5.5103,-17.8299,-14.1330,64.5092,261.9053,0
7486,70.0891,22.8547,3.1780,0.1328,0.0773,39.9608,52.7026,9.0460,3.2454,226.9620,0
9394,32.1456,20.0292,2.5664,0.3962,0.2402,-27.9947,-25.8885,-14.5929,8.5640,180.5900,0
11290,44.1086,16.4540,2.9540,0.2813,0.1595,8.0586,22.7570,11.0314,0.6770,187.9470,0
5702,23.2007,9.7733,2.2788,0.5579,0.2921,-25.5851,-17.1035,-10.6575,30.7414,52.9858,0
15348,55.4982,51.7795,3.1203,0.1750,0.1152,15.2896,41.2633,15.6825,61.6744,145.1107,0
4337,22.2487,0.0000,2.2565,0.8199,0.4349,-22.3546,-17.0073,-0.0001,28.0190,110.6100,0
7206,24.4389,20.3553,2.6004,0.2861,0.1568,-7.4896,-12.3491,8.9482,26.1127,228.2730,0
4085,41.7967,17.4889,2.8782,0.2660,0.1383,-4.6361,15.0798,9.3551,17.5370,206.4700,0
10767,61.6932,20.7153,3.1707,0.1903,0.1077,-14.6646,35.8305,-10.0198,9.2090,203.0490,0
7507,21.2302,12.2991,2.2889,0.4627,0.2442,0.5732,-6.5729,-10.8021,43.8353,165.1580,0
3064,13.1000,10.3364,2.2109,0.7877,0.5077,12.7159,6.3277,9.8957,39.6200,160.7340,0
694,30.9688,19.9094,2.8837,0.3987,0.2320,30.7659,28.6154,-14.9461,69.0844,37.6417,0
3159,28.1746,18.2959,2.4464,0.3971,0.2236,-5.5426,11.1219,7.5284,47.4070,95.4522,0
16400,104.5871,37.1702,3.2437,0.2562,0.1144,-80.5862,-99.2532,-24.5775,8.4966,393.3124,0
18583,32.6610,12.4938,2.6364,0.4749,0.2801,-31.6254,3.8473,12.4469,62.3367,159.5799,0
17227,21.3864,16.5732,2.3528,0.7327,0.3852,6.4741,27.3670,10.4684,36.1593,64.9341,0
18666,44.6647,17.1665,2.6443,0.2816,0.1663,17.9543,43.8893,-6.4795,78.5736,245.8811,0
1704,46.9247,20.2722,2.7486,0.3140,0.1722,31.8542,31.0256,16.7207,5.1486,270.2110,0
556,33.2252,13.5700,2.5735,0.4619,0.2577,-27.9605,-15.7714,-9.7642,15.7100,76.5837,0
5805,73.2800,30.9372,3.8598,0.1554,0.0785,14.5414,68.0356,-27.0649,1.0024,230.9070,0
13012,120.9224,71.0392,3.6757,0.2054,0.0901,-58.0453,-141.1602,45.3024,21.4663,399.0409,0
17858,18.7485,0.6007,2.2685,0.7225,0.4474,-1.9626,-0.1305,-5.6280,89.6541,210.2822,0
9309,82.6686,15.6000,2.6439,0.4041,0.2509,-114.0200,52.8269,11.2740,5.8704,272.4480,0
5086,23.6235,18.3227,2.5676,0.3870,0.1962,7.7972,-17.9258,5.5092,12.4528,208.2030,0
1928,35.9040,26.8518,2.8794,0.1954,0.1076,31.3797,33.4534,15.2017,87.6718,126.3550,0
16206,23.6883,6.0430,2.4771,0.7533,0.5417,-3.3438,-18.5123,4.8497,82.5746,198.4000,0
593,20.1958,7.2301,2.1287,0.7509,0.3829,3.5491,-11.1057,-5.4224,17.9072,137.7140,0

In [98]:
df.loc[df['class'] == 1]

Empty DataFrame
Columns: [fLength, fWidth, fSize, fConc, fConc1, fAsym, fM3Long, fM3Trans, fAlpha, fDist, class]
Index: []

In [106]:
df['class'] = df['class'].astype(str).str.strip()
df['class'] = (df['class'] == 'g').astype(int)

In [107]:
print(df['class'].value_counts())

class
0    19020
Name: count, dtype: int64

In [108]:
df['class'] = df['class'].astype(str).str.strip().str.lower()

In [ ]:
df.sample(10)

,fLength,fWidth,fSize,fConc,fConc1,fAsym,fM3Long,fM3Trans,fAlpha,fDist,class
6628,35.1096,15.7362,2.8341,0.4220,0.2249,32.2606,31.9554,3.2093,15.3100,199.1660,0
11278,58.9667,14.9409,3.0661,0.2799,0.1636,45.8596,26.7538,-12.7487,11.5910,213.6300,0
479,66.7069,26.9460,2.9710,0.2694,0.1448,21.8764,31.9335,-18.6999,5.3847,256.1180,0
5064,92.4484,27.5454,3.4125,0.1447,0.0733,90.4871,84.0013,21.7061,13.3408,255.6600,0
5359,34.3872,31.6236,3.2924,0.2198,0.1217,21.1503,28.0159,-25.0545,20.7695,106.6290,0
14808,63.9326,31.0390,3.3938,0.2443,0.1254,49.2973,59.7712,-11.0097,33.1940,273.4190,0
9818,37.4641,20.2337,3.0022,0.2786,0.1517,-12.5520,10.7198,14.7785,6.8670,167.4490,0
2831,30.3270,29.3758,2.7368,0.2493,0.1274,25.1576,17.9015,-18.1123,81.3672,157.6790,0
15855,182.4738,37.1706,2.9856,0.2622,0.1841,-265.0052,172.5351,7.6725,14.3907,139.6862,0
14912,48.3457,9.8713,2.7987,0.3950,0.2066,-10.2163,-20.0218,5.7925,46.4487,162.8426,0

:

In [5]:
import threading
import time

def greet(name):
    print(f"Hello, {name}!")
    time.sleep(2)
    print(f"Goodbye, {name}!")

# Create two threads
t1 = threading.Thread(target=greet, args=("Alice",))
t2 = threading.Thread(target=greet, args=("Bob",))

# Start both threads
t1.start()
t2.start()

# Wait for both to finish
t1.join()
t2.join()

Hello, Alice!Hello, Bob!

Goodbye, Alice!Goodbye, Bob!